### ISSUE TITLE
Two box characters always present in live p5 panel

### ISSUE THREAD

**Issue by Tompouce-onGit** [filipesabella/vscode-live-p5#6] opened 2019-12-20 21:58 UTC
When opening the live p5 panel, there are always two box characters present in the window, even if the `setup` and `draw` functions are empty:

*With empty setup and draw*
![with empty setup and draw](https://i.imgur.com/7maxScE.png)
*With a simple background*
![with a simple background](https://i.imgur.com/8MZjk8K.png)

**Comment by filipesabella** [comment] 2020-01-05 12:25
Hey there @Tompouce-onGit, thanks for the report and apologies for the delay.

I gotta say I'm a little stumped on this one, as I can't reproduce it nor really reason about how these characters might be displayed.

Can you help me a little further perhaps?
Open the developer tools in vscode with the p5-live panel open and execute the following:

```document.querySelector('webview').openDevTools()```

That will open a new tab in the developer tools, and that one will be in the context of the webview.
In that, navigate through the html tree, inside the iframe's document, and try and see where these characters are being printed exactly.

Mine looks like this for reference:
![image](https://user-images.githubusercontent.com/33415/71780105-3132b880-2f9d-11ea-8179-a95e2af6faa2.png)

**Comment by filipesabella** [comment] 2020-03-09 00:51
hey @Tompouce-onGit, I'll close this for now, but please feel free to follow-up.

**Closed as completed by filipesabella** 2020-03-09 00:51 UTC
